version: '2'
services:
  go-web-app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - VIRTUAL_HOST=duckysdockside.com
      - LETSENCRYPT_HOST=duckysdockside.com
      - DDS_SERVICE_VERSION=PRODUCTION
      - DDS_LOGFILE=/go/bin/logs/duckydockside.log
      - DDS_EVENTSDATAFILE=/go/bin/data/events.json
      - DDS_FOODMENUDATAFILE=/go/bin/data/foodmenu.json
      - DDS_STATIC_LOCATION=/go/bin/static/
      - DDS_HTML_LOCATION=html/
      - DDS_TEMPLATE_LOCATION=/go/bin/templates/
      - DDS_SERVER_PORT=:80
      - DDS_WEATHERAPI_TOKEN=71c3f677cbb242889f4173533220505
      - DDS_ADMIN_PASSWORD=DocksideSecrets101!
      #sslmode = REQUIRED
