version: '2'
services:
  go-web-app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - VIRTUAL_HOST=duckysdockside.com
      - LETSENCRYPT_HOST=duckysdockside.com
      - DDS_SERVICE_VERSION=PRODUCTION
      - DDS_LOGFILE=/go/bin/logs/duckydockside.log
      - DDS_STATIC_LOCATION=/go/bin/static/
      - DDS_SERVER_PORT=:80
      - DDS_ADMIN_PASSWORD=DocksideSecrets101!
      #sslmode = REQUIRED
