version: '2'
services:
  go-web-app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - VIRTUAL_HOST=bytesupply.com
      - LETSENCRYPT_HOST=bytesupply.com
      - DDS_SERVICE_VERSION=PRODUCTION
      - DDS_LOGFILE=/go/bin/log/duckydockside.log
      - DDS_MSGFILE=/go/bin/log/message.log
      - DDS_STATIC_LOCATION=/go/bin/static/
      - DDS_SERVER_PORT=:80
      - DDS_ADMIN_PASSWORD=a6bd3f10339b2d39aaa6175484a38173c1061f4a
      #sslmode = REQUIRED
